spring:
  application:
    name: dify-demo

dify:
  url: https://dify.yourcompay.com/v1/chat-messages
  baseUrl: https://dify.yourcompay.com/v1
  apiKey: app-y67TVu9T8tZ6r2UUMBJ6wm8R
  key:
    test: app-y67TVu9T8tZ6r2UUMBJ6wm8R
